version: "3.6"
services:

    api-geo:
        container_name: api-geo
        ports:
          - 8000:80
          - 8001:443
        build:
          context: ./API-GEO
          dockerfile: API-GEO/Dockerfile
        depends_on:
          - rabbitmq
          - mysql
          - geocodificador

    rabbitmq:
        container_name: rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
        environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
        image: rabbitmq:3.8.9-management
        
    mysql:
      container_name: mysql
      restart: always
      image: mysql:8.0.21
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: 'db'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'user'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'password'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'admin1234'
      expose:
        - '3306'
      volumes:
        - my-db:/var/lib/mysql
        - ./Data/GeoDB:/docker-entrypoint-initdb.d

    geocodificador:
        container_name: geocodificador
        ports:
          - 9000:80
          - 9001:443
        build:
          context: ./Geocodificador
          dockerfile: Geocodificador/Dockerfile

volumes:
  my-db: